(() => {
  const $=id=>document.getElementById(id);const toastEl=$("ppToast");let compiler="";
  function toast(s){toastEl.textContent=s;toastEl.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove("show"),1700)}
  function row(kind,data={input:"",output:"",hidden:false}){const div=document.createElement("div");div.className="testRow";div.innerHTML=`<div class="testHead"><b>${kind}</b><div class="vs-row">${kind==="Test"?`<label class="vs-toggle"><input class="hidden" type="checkbox" ${data.hidden?"checked":""}> Hidden</label>`:""}<button class="miniBtn runRef">Generate output</button><button class="miniBtn danger remove">Remove</button></div></div><label>Input<textarea class="input">${escapeHtml(data.input)}</textarea></label><label>Expected output<textarea class="output">${escapeHtml(data.output)}</textarea></label>`;div.querySelector(".remove").onclick=()=>{div.remove();preview()};div.querySelector(".runRef").onclick=()=>generate(div);div.addEventListener("input",preview);div.addEventListener("change",preview);return div;}
  function escapeHtml(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
  async function discover(){if(compiler)return compiler;const r=await fetch("https://wandbox.org/api/list.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const list=await r.json();const cs=list.filter(c=>String(c.language||"").toLowerCase().includes("c#"));if(!cs.length)throw new Error("No C# compiler available");cs.sort((a,b)=>{const s=x=>(String(x.name).toLowerCase().includes("dotnet")?100:0)+(String(x.name).toLowerCase().includes("mono")?80:0)+(String(x.name).toLowerCase().includes("head")?20:0);return s(b)-s(a)});compiler=cs[0].name;return compiler;}
  async function run(code,stdin){const c=await discover();const r=await fetch("https://wandbox.org/api/compile.json",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,compiler:c,stdin,options:"","compiler-option-raw":"","runtime-option-raw":""})});if(!r.ok)throw new Error(`Compiler HTTP ${r.status}`);const d=await r.json();const err=[d.compiler_error,d.compiler_output,d.program_error,d.signal].filter(Boolean).join("\n").trim();if(String(d.status||"0")!=="0")throw new Error(err||"Reference solution failed");return String(d.program_output||"");}
  async function generate(div){const btn=div.querySelector(".runRef");btn.disabled=true;btn.textContent="Running…";try{div.querySelector(".output").value=await run($("solution").value,div.querySelector(".input").value);preview();toast("Expected output generated")}catch(e){toast(String(e.message||e))}finally{btn.disabled=false;btn.textContent="Generate output"}}
  function collect(container){return Array.from(container.querySelectorAll(".testRow")).map(r=>({input:r.querySelector(".input").value,output:r.querySelector(".output").value,...(r.querySelector(".hidden")?{hidden:r.querySelector(".hidden").checked}:{})}))}
  function obj(){return{id:$("id").value.trim()||"problem",title:$("title").value.trim()||"Untitled",level:$("level").value,statement:$("statement").value,starter:$("starter").value,examples:collect($("examples")),tests:collect($("tests")),hints:$("hints").value.split(/\n+/).map(x=>x.trim()).filter(Boolean),tags:$("tags").value.split(",").map(x=>x.trim()).filter(Boolean)}}
  function preview(){$("preview").textContent=JSON.stringify(obj(),null,2)}
  function download(){const blob=new Blob([JSON.stringify([obj()],null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`${obj().id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  $("addExample").onclick=()=>{$("examples").appendChild(row("Example"));preview()};$("addTest").onclick=()=>{$("tests").appendChild(row("Test"));preview()};$("download").onclick=download;$("refresh").onclick=preview;$("copy").onclick=async()=>{await navigator.clipboard.writeText($("preview").textContent);toast("JSON copied")};$("theme").onclick=()=>{const d=document.body.dataset.theme==="dark";document.body.dataset.theme=d?"light":"dark";$("theme").textContent=d?"Dark":"Light"};["id","title","level","statement","tags","hints","starter","solution"].forEach(id=>$(id).addEventListener("input",preview));$("examples").appendChild(row("Example",{input:"5\n",output:""}));$("tests").appendChild(row("Test",{input:"5\n",output:"",hidden:false}));preview();
})();
